# Generated by Django 4.2.4 on 2023-08-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpitem',
            options={'ordering': ('order', 'name', 'id')},
        ),
        migrations.AddField(
            model_name='helpitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
