# Generated by Django 3.2.15 on 2022-08-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_data_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseformatsentencebuilder',
            name='sentence_translated_audio',
        ),
        migrations.RemoveField(
            model_name='exerciseformattranslation',
            name='translation_image',
        ),
        migrations.AddField(
            model_name='exerciseformattranslation',
            name='translation_source_image',
            field=models.ImageField(blank=True, help_text='Optional if provided source text instead, otherwise required', null=True, upload_to='exercises-exerciseformat-translation'),
        ),
        migrations.AddField(
            model_name='exerciseformattranslation',
            name='translation_source_text',
            field=models.TextField(blank=True, help_text='Optional if provided source image instead, otherwise required', null=True),
        ),
        migrations.AlterField(
            model_name='exerciseformatsentencebuilder',
            name='sentence_source',
            field=models.TextField(blank=True, help_text='Provide an original source sentence in one language, which will be translated below. Optional if supplying audio instead, otherwise required', null=True),
        ),
        migrations.AlterField(
            model_name='exerciseformatsentencebuilder',
            name='sentence_translated',
            field=models.TextField(help_text='Provide a translated sentence of the above source sentence. This translated sentence will be jumbled and the student will have to rebuild it.'),
        ),
    ]
