# Generated by Django 4.2.4 on 2023-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_data_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions_image_width_percent',
            field=models.IntegerField(blank=True, help_text='Optional. Set the percentage width of the instructions box. Images will fill width of instructions box by default.', null=True, verbose_name='Instructions image width (%)'),
        ),
    ]
