# Generated by Django 4.2.16 on 2024-09-18 09:46

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_fontsize_exercise_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='(Optional) Provide the URL of a YouTube or Vimeo video to include the embedded video in the exercise instructions.', null=True),
        ),
    ]
