# Generated by Django 4.2.16 on 2024-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_instructions_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseformatsentencebuilder',
            name='sentence_translated',
            field=models.TextField(help_text='Provide a translated/transcribed sentence of the above source text/audio. The sentence will be separated into words automatically. If you instead want to set custom breakpoints to group words together then simply insert a * at each point, e.g. "this is * an example of * multiple words grouped * together". The words in this target text will be jumbled and the student will have to rebuild it in the correct order.', verbose_name='target text'),
        ),
    ]
