# Generated by Django 5.2.9 on 2025-12-16 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exerciseformatsentencebuilder_sentence_translated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='exercises-importdata')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_data_file_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='import_data_file',
            field=models.ForeignKey(blank=True, help_text='If this exercise was created via a data import file (e.g. csv file) then it will be linked here', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.importdatafile'),
        ),
    ]
