# Generated by Django 3.2.13 on 2022-06-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, to='exercises.SchoolClass'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.language'),
        ),
    ]
