# Generated by Django 4.2.9 on 2024-02-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_language',
        ),
    ]
