# Generated by Django 5.2.7 on 2025-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_options_remove_user_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, help_text='Provide an API key to export data via API with this user', max_length=255, null=True),
        ),
    ]
